import Foundation
import Combine
import MediaPlayer

// MARK: - Debug Errors
enum DebugError: LocalizedError {
    case chatGPTNotConfigured
    case noLocalMusic

    var errorDescription: String? {
        switch self {
        case .chatGPTNotConfigured:
            return "ChatGPT/AI service is not configured. Add your API key in settings."
        case .noLocalMusic:
            return "No local Apple Music library content found on this device."
        }
    }
}

// MARK: - Music Debug ViewModel
@MainActor
final class MusicDebugViewModel: ObservableObject {
    @Published var testSuggestion: MusicSuggestion?
    @Published var libraryCount: Int = 0
    @Published var isTesting: Bool = false
    @Published var error: Error?
    
    // Madlib parameters
    @Published var selectedWorkoutPhase: WorkoutPhase = .starting
    @Published var selectedIntensity: Intensity = .medium
    @Published var currentHeartRate: Double = 150
    @Published var currentDistance: Double = 5.0
    @Published var currentTime: Double = 30
    @Published var preferLibrarySelection: Bool = false
    
    // Dependencies
    private let profileManager = UserProfileManager.shared
    private let musicManager = MusicPlaybackManager.shared
    private let musicCoordinator = WorkoutMusicCoordinator.shared
    private let chatGPTService = ChatGPTService.shared
    
    private var cancellables = Set<AnyCancellable>()
    
    init() {
        setupBindings()
        loadLibraryCount()
    }
    
    private func setupBindings() {
        Publishers.Merge3(
            profileManager.$lastError.compactMap { $0 },
            musicManager.$playbackError.compactMap { $0 },
            chatGPTService.$lastError.compactMap { $0 }
        )
        .assign(to: &$error)
    }
    
    // MARK: - Computed Properties
    var isMusicAuthorized: Bool {
        profileManager.isMusicAuthorized
    }
    
    var musicAuthorizationStatus: String {
        profileManager.musicAuthorizationStatus.description
    }
    
    var isChatGPTConfigured: Bool {
        chatGPTService.isConfigured
    }
    
    var currentSong: MusicSong? {
        musicManager.currentSong
    }
    
    var isPlaying: Bool {
        musicManager.isPlaying
    }
    
    var isGeneratingSuggestion: Bool {
        musicManager.isGeneratingSuggestion
    }
    
    var lastSuggestion: MusicSuggestion? {
        // Only show suggestions that were actually generated by ChatGPT tests
        testSuggestion
    }
    
    var isWorkoutActive: Bool {
        musicCoordinator.isWorkoutActive
    }
    
    // MARK: - Actions
    func requestMusicAuthorization() {
        profileManager.requestMusicAuthorization()
    }
    
    func loadLibraryCount() {
        let query = MPMediaQuery.songs()
        libraryCount = query.items?.count ?? 0
    }
    
    func testMusicSuggestion() async {
        guard isChatGPTConfigured else {
            error = DebugError.chatGPTNotConfigured
            return
        }
        
        isTesting = true
        error = nil // Clear any previous errors
        
        defer { isTesting = false }
        
        do {
            print("🧪 Starting ChatGPT test...")
            
            // Create a test context
            let testContext = MusicContext(
                currentHeartRate: 150,
                targetHeartRate: 160,
                currentIntensity: .medium,
                timeRemainingInSegment: 300,
                currentSongEndingIn: 30,
                userPreferences: profileManager.userProfile.musicPreferences,
                recentSongs: [],
                currentDistance: 1000.0, // 1km for testing
                currentPace: 3.0, // 3 m/s for testing
                isActive: true
            )
            
            print("🧪 Test context created, calling ChatGPT...")
            
            let suggestion = try await withTimeout(seconds: 30) {
                try await self.chatGPTService.generateMusicSuggestion(
                    context: testContext,
                    userPreferences: self.profileManager.userProfile.musicPreferences
                )
            }
            
            print("✅ ChatGPT test successful: \(suggestion.songTitle) by \(suggestion.artist)")
            testSuggestion = suggestion
            
        } catch {
            print("❌ ChatGPT test failed: \(error)")
            self.error = error
        }
    }
    
    func generateMadlibSuggestion() async {
        guard isChatGPTConfigured else {
            error = DebugError.chatGPTNotConfigured
            return
        }
        
        isTesting = true
        error = nil
        
        defer { isTesting = false }
        
        do {
            print("🎭 Starting Madlib music generation...")
            print("📊 Parameters: Phase=\(selectedWorkoutPhase.displayName), Intensity=\(selectedIntensity.label), HR=\(Int(currentHeartRate)), Distance=\(currentDistance)km, Time=\(Int(currentTime))min, Library=\(preferLibrarySelection)")
            
            // Calculate target heart rate based on intensity
            let targetHeartRate = calculateTargetHeartRate(for: selectedIntensity)
            
            // Calculate pace from distance and time
            let pace = currentTime > 0 ? (currentDistance * 1000) / (currentTime * 60) : 0 // m/s
            
            // Calculate time remaining in segment based on workout phase
            let timeRemainingInSegment = calculateTimeRemainingInSegment()
            
            // Create context based on madlib parameters
            let madlibContext = MusicContext(
                currentHeartRate: Int(currentHeartRate),
                targetHeartRate: targetHeartRate,
                currentIntensity: selectedIntensity,
                timeRemainingInSegment: timeRemainingInSegment,
                currentSongEndingIn: 30, // Assume song ending in 30 seconds
                userPreferences: profileManager.userProfile.musicPreferences,
                recentSongs: [],
                currentDistance: currentDistance * 1000, // Convert to meters
                currentPace: pace,
                isActive: true
            )
            
            print("🎭 Madlib context created, calling ChatGPT...")
            
            // Generate suggestion based on madlib parameters
            let suggestion: MusicSuggestion
            
            if preferLibrarySelection {
                // Force library selection
                suggestion = try await chatGPTService.getRandomLibrarySong(
                    preferences: profileManager.userProfile.musicPreferences,
                    intensity: selectedIntensity
                )
            } else {
                // Use normal generation with madlib context
                suggestion = try await withTimeout(seconds: 30) {
                    try await self.chatGPTService.generateMusicSuggestion(
                        context: madlibContext,
                        userPreferences: self.profileManager.userProfile.musicPreferences
                    )
                }
            }
            
            print("✅ Madlib generation successful: \(suggestion.songTitle) by \(suggestion.artist)")
            testSuggestion = suggestion
            
        } catch {
            print("❌ Madlib generation failed: \(error)")
            self.error = error
        }
    }
    
    func playAppleMusicSuggestion() async {
        guard let suggestion = testSuggestion else { return }
        
        print("🎵 About to call musicManager.playAppleMusicSuggestion with: '\(suggestion.songTitle)' by \(suggestion.artist)")
        
        await musicManager.playAppleMusicSuggestion(suggestion)
        
        print("🎵 musicManager.playAppleMusicSuggestion call completed")
    }
    
    // MARK: - Helper Methods for Madlib
    
    private func calculateTargetHeartRate(for intensity: Intensity) -> Int {
        // Use the same heart rate zones as the ChatGPT service
        switch intensity {
        case .easy:
            return 130 // Middle of 100-140 range
        case .medium:
            return 140 // Middle of 120-160 range
        case .hard:
            return 155 // Middle of 130-180 range
        }
    }
    
    private func calculateTimeRemainingInSegment() -> TimeInterval {
        switch selectedWorkoutPhase {
        case .starting:
            return 300 // 5 minutes remaining
        case .midway:
            return 180 // 3 minutes remaining
        case .finishing:
            return 60 // 1 minute remaining
        case .interval:
            return 120 // 2 minutes remaining
        case .recovery:
            return 240 // 4 minutes remaining
        }
    }
    
    // MARK: - Preset Scenarios
    
    func setEasy5KScenario() {
        selectedWorkoutPhase = .midway
        selectedIntensity = .easy
        currentHeartRate = 130
        currentDistance = 3.0
        currentTime = 25
        preferLibrarySelection = true
        print("🎯 Set Easy 5K scenario: Easy intensity, 130 BPM, 3km in 25min")
    }
    
    func setIntervalScenario() {
        selectedWorkoutPhase = .interval
        selectedIntensity = .hard
        currentHeartRate = 170
        currentDistance = 1.0
        currentTime = 4
        preferLibrarySelection = false
        print("🎯 Set Interval scenario: Hard intensity, 170 BPM, 1km in 4min")
    }
    
    func setFinishStrongScenario() {
        selectedWorkoutPhase = .finishing
        selectedIntensity = .hard
        currentHeartRate = 180
        currentDistance = 8.0
        currentTime = 45
        preferLibrarySelection = false
        print("🎯 Set Finish Strong scenario: Hard intensity, 180 BPM, 8km in 45min")
    }
    
    func setRecoveryScenario() {
        selectedWorkoutPhase = .recovery
        selectedIntensity = .easy
        currentHeartRate = 110
        currentDistance = 2.0
        currentTime = 20
        preferLibrarySelection = true
        print("🎯 Set Recovery scenario: Easy intensity, 110 BPM, 2km in 20min")
    }
    
    // Helper function for timeout handling
    private func withTimeout<T>(seconds: TimeInterval, operation: @escaping () async throws -> T) async throws -> T {
        return try await withThrowingTaskGroup(of: T.self) { group in
            group.addTask {
                try await operation()
            }
            
            group.addTask {
                try await Task.sleep(nanoseconds: UInt64(seconds * 1_000_000_000))
                throw TimeoutError()
            }
            
            guard let result = try await group.next() else {
                throw TimeoutError()
            }
            
            group.cancelAll()
            return result
        }
    }
    
    func generateAndPlayTestSuggestion() async {
        print("🎵 Starting full test: ChatGPT + Apple Music")
        
        // 1) Ensure Apple Music authorization
        if !isMusicAuthorized {
            print("🔐 Requesting music authorization...")
            await withCheckedContinuation { continuation in
                profileManager.requestMusicAuthorization()
                DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
                    continuation.resume()
                }
            }
            if !isMusicAuthorized {
                print("❌ Music authorization failed")
                self.error = MusicError.notAuthorized
                return
            }
        }
        print("✅ Music authorization confirmed")

        // 2) Ensure there is some content locally
        loadLibraryCount()
        print("📚 Library count: \(libraryCount)")
        if libraryCount == 0 {
            print("⚠️ No local music found, but continuing test...")
            self.error = DebugError.noLocalMusic
            // Continue anyway to exercise the pipeline; playback may still fail
        }

        // 3) Generate suggestion
        print("🤖 Generating ChatGPT suggestion...")
        await testMusicSuggestion()
        
        // Check if ChatGPT generation failed (not just warnings)
        if let error = self.error, error is ChatGPTError {
            print("❌ ChatGPT generation failed: \(error)")
            return
        }

        // 4) Play it (even if there are warnings like noLocalMusic)
        print("🎵 Attempting to play suggestion...")
        await playTestSuggestion()
        print("✅ Full test completed")
    }
    
    func playTestSuggestion() async {
        guard let suggestion = testSuggestion else { 
            print("❌ No test suggestion available to play")
            return 
        }
        
        print("🎵 About to call musicManager.playSuggestedSong with: '\(suggestion.songTitle)' by \(suggestion.artist)")
        await musicManager.playSuggestedSong(suggestion)
        print("🎵 musicManager.playSuggestedSong call completed")
    }
    
    func testSimplePlayback() async {
        print("🧪 Testing simple music playback...")
        
        // Clear any previous ChatGPT suggestion since this is not a ChatGPT test
        testSuggestion = nil
        
        // Check authorization
        let authStatus = MPMediaLibrary.authorizationStatus()
        print("🔐 Music authorization status: \(authStatus.rawValue)")
        
        if authStatus != .authorized {
            print("❌ Music not authorized. Please authorize in Profile → Music Preferences")
            return
        }
        
        // Get all songs
        let query = MPMediaQuery.songs()
        guard let songs = query.items, !songs.isEmpty else {
            print("❌ No songs found in library")
            return
        }
        
        print("📚 Found \(songs.count) songs in library")
        
        // Try to play the first song
        let firstSong = songs[0]
        print("🎵 Attempting to play: '\(firstSong.title ?? "Unknown")' by \(firstSong.artist ?? "Unknown")")
        
        // Use the music manager's playSong method directly
        await musicManager.playSongDirectly(firstSong)
    }
    
    func debugLibraryContents() async {
        print("🔍 Debugging library contents...")
        
        let query = MPMediaQuery.songs()
        guard let songs = query.items, !songs.isEmpty else {
            print("❌ No songs found in library")
            return
        }
        
        print("📚 Total songs in library: \(songs.count)")
        print("🎵 First 10 songs:")
        
        for (index, song) in songs.prefix(10).enumerated() {
            print("   \(index + 1). '\(song.title ?? "Unknown")' by \(song.artist ?? "Unknown")")
        }
        
        // Check if the suggested song exists
        if let suggestion = testSuggestion {
            print("🔍 Looking for suggested song: '\(suggestion.songTitle)' by \(suggestion.artist)")
            
            let matchingSongs = songs.filter { song in
                if let title = song.title, let artist = song.artist {
                    return title.lowercased().contains(suggestion.songTitle.lowercased()) ||
                           artist.lowercased().contains(suggestion.artist.lowercased())
                }
                return false
            }
            
            if !matchingSongs.isEmpty {
                print("✅ Found \(matchingSongs.count) matching songs:")
                for song in matchingSongs {
                    print("   - '\(song.title ?? "Unknown")' by \(song.artist ?? "Unknown")")
                }
            } else {
                print("❌ No matching songs found for suggestion")
            }
        }
    }
    
    func testFallbackLogic() async {
        print("🧪 Testing fallback logic with non-existent song...")
        
        // Clear any previous ChatGPT suggestion since this is not a ChatGPT test
        testSuggestion = nil
        
        // Create a fake suggestion that definitely doesn't exist
        let fakeSuggestion = MusicSuggestion(
            songTitle: "This Song Definitely Does Not Exist",
            artist: "Fake Artist Name",
            reason: "Testing fallback logic",
            mood: .energetic,
            confidence: 0.5
        )
        
        print("🎵 Testing with fake suggestion: '\(fakeSuggestion.songTitle)' by \(fakeSuggestion.artist)")
        
        // Try to play this fake suggestion
        await musicManager.playSuggestedSong(fakeSuggestion)
        
        print("✅ Fallback test completed")
    }
    
    func testMattMemsPlayback() async {
        print("🧪 Testing playback with existing artist 'Matt Mems'...")
        
        // Clear any previous ChatGPT suggestion since this is not a ChatGPT test
        testSuggestion = nil
        
        // Create a suggestion for an artist we know exists
        let mattMemsSuggestion = MusicSuggestion(
            songTitle: "Some Song That Doesn't Exist",
            artist: "Matt Mems",
            reason: "Testing with existing artist",
            mood: .energetic,
            confidence: 0.5
        )
        
        print("🎵 Testing with Matt Mems suggestion: '\(mattMemsSuggestion.songTitle)' by \(mattMemsSuggestion.artist)")
        
        // Try to play this suggestion
        await musicManager.playSuggestedSong(mattMemsSuggestion)
        
        print("✅ Matt Mems test completed")
    }
    
    func testCurrentSuggestionPlayback() async {
        print("🧪 Testing playback with current ChatGPT suggestion...")
        
        guard let suggestion = testSuggestion else {
            print("❌ No current suggestion to test")
            return
        }
        
        print("🎵 Testing with current suggestion: '\(suggestion.songTitle)' by \(suggestion.artist)")
        
        // Try to play the current suggestion directly
        await musicManager.playSuggestedSong(suggestion)
        
        print("✅ Current suggestion test completed")
    }
    
    func startTestWorkout() {
        let testSegments = [
            RunSegment(intensity: .easy, target: .time(seconds: 300)),
            RunSegment(intensity: .medium, target: .time(seconds: 180)),
            RunSegment(intensity: .hard, target: .time(seconds: 120))
        ]
        
        musicCoordinator.startWorkoutMusic(segments: testSegments)
    }
    
    func stopTestWorkout() {
        musicCoordinator.stopWorkoutMusic()
    }
    
    func playMusic() {
        musicManager.play()
    }
    
    func pauseMusic() {
        musicManager.pause()
    }
    
    func skipToNext() {
        musicManager.skipToNext()
    }
    
    func skipToPrevious() {
        musicManager.skipToPrevious()
    }
    
    func refreshAuthorizationAndLibrary() {
        // For initial prompt, call requestMusicAuthorization() from the UI
        loadLibraryCount()
    }
    
    func clearError() {
        error = nil
    }
    
    func debugSearchResults() async {
        guard let suggestion = testSuggestion else {
            print("❌ No suggestion to debug")
            return
        }
        
        print("🔍 Debugging search results for: '\(suggestion.songTitle)' by \(suggestion.artist)")
        
        // Get all songs and show what would be found
        let allSongsQuery = MPMediaQuery.songs()
        guard let allSongs = allSongsQuery.items, !allSongs.isEmpty else {
            print("❌ No songs in library")
            return
        }
        
        print("📚 Total songs in library: \(allSongs.count)")
        
        // Test exact title search
        let exactQuery = MPMediaQuery.songs()
        let exactPredicate = MPMediaPropertyPredicate(
            value: suggestion.songTitle,
            forProperty: MPMediaItemPropertyTitle,
            comparisonType: .contains
        )
        exactQuery.addFilterPredicate(exactPredicate)
        
        if let exactResults = exactQuery.items, !exactResults.isEmpty {
            print("✅ Exact title search found \(exactResults.count) results:")
            for (index, song) in exactResults.prefix(3).enumerated() {
                print("   \(index + 1). '\(song.title ?? "Unknown")' by \(song.artist ?? "Unknown")")
            }
        } else {
            print("❌ Exact title search found no results")
        }
        
        // Test fuzzy search
        let fuzzyMatches = findFuzzyMatches(in: allSongs, for: suggestion)
        if !fuzzyMatches.isEmpty {
            print("🔍 Fuzzy search found \(fuzzyMatches.count) results:")
            for (index, song) in fuzzyMatches.prefix(5).enumerated() {
                print("   \(index + 1). '\(song.title ?? "Unknown")' by \(song.artist ?? "Unknown")")
            }
        } else {
            print("❌ Fuzzy search found no results")
        }
        
        // Test artist search
        let targetArtist = suggestion.artist.lowercased()
        let artistMatches = allSongs.filter { song in
            guard let artist = song.artist?.lowercased() else { return false }
            return artist.contains(targetArtist) || targetArtist.contains(artist)
        }
        
        if !artistMatches.isEmpty {
            print("🎤 Artist search found \(artistMatches.count) results:")
            for (index, song) in artistMatches.prefix(3).enumerated() {
                print("   \(index + 1). '\(song.title ?? "Unknown")' by \(song.artist ?? "Unknown")")
            }
        } else {
            print("❌ Artist search found no results")
        }
    }
    
    private func findFuzzyMatches(in songs: [MPMediaItem], for suggestion: MusicSuggestion) -> [MPMediaItem] {
        let targetTitle = suggestion.songTitle.lowercased()
        let targetArtist = suggestion.artist.lowercased()
        
        var matches: [(item: MPMediaItem, score: Int)] = []
        
        for song in songs {
            guard let title = song.title?.lowercased(),
                  let artist = song.artist?.lowercased() else { continue }
            
            var score = 0
            
            // Exact title match (highest priority)
            if title == targetTitle {
                score += 100
            }
            // Title contains target (high priority)
            else if title.contains(targetTitle) {
                score += 80
            }
            // Target contains title (medium priority)
            else if targetTitle.contains(title) {
                score += 60
            }
            // Word-by-word matching
            else {
                let titleWords = title.components(separatedBy: CharacterSet.whitespaces.union(CharacterSet.punctuationCharacters)).filter { !$0.isEmpty }
                let targetWords = targetTitle.components(separatedBy: CharacterSet.whitespaces.union(CharacterSet.punctuationCharacters)).filter { !$0.isEmpty }
                
                for targetWord in targetWords {
                    for titleWord in titleWords {
                        if titleWord.contains(targetWord) || targetWord.contains(titleWord) {
                            score += 20
                        }
                    }
                }
            }
            
            // Artist matching bonus
            if artist == targetArtist {
                score += 50
            } else if artist.contains(targetArtist) || targetArtist.contains(artist) {
                score += 30
            }
            
            // Only include songs with some match
            if score > 0 {
                matches.append((song, score))
            }
        }
        
        // Sort by score (highest first) and return items
        return matches.sorted { $0.score > $1.score }.map { $0.item }
    }
}
